---
title: "experiment 2"
format: html
editor: visual
---

## Import packages

```{r}
library(conflicted)  
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")

library(tidyverse)
library(tidyboot)
library(lme4)
library(here)
library(jsonlite)
library(ggthemes)
library(plotly)


theme_set(theme_few())
```

## Read in data

```{r}

d.allmsg <- read_csv(here('analysis/2_experiment_2/coded.csv'))%>%
  rename_with(~ gsub("\\.x$", "", .x), ends_with(".x")) %>%
  select(-ends_with(".y"))

```

```{r}
#used this to correct accidental miscodes as pn, as that's essentially the default msg
compare.msg <- d.allmsg %>%
  filter(str_detect(coding, "pn"), !str_detect(coding, "[sb]"), round != 1) %>%
  mutate(extracted = str_extract_all(text, "\\d+")) %>%
  filter(map_lgl(extracted, ~ length(.x) == 2)) %>%
  mutate(
    num1 = as.numeric(map_chr(extracted, 1)),
    num2 = as.numeric(map_chr(extracted, 2))
  ) %>%
  filter(
    !((num1 == nRabbits & num2 == nSquirrels) | (num1 == nSquirrels & num2 == nRabbits)), 
  ) %>%
  select(-extracted, -sender.name, -recipient, -treatment, -direction, -guess, -confidence)

compare.msg <- compare.msg %>%
  group_by(gameID) %>%
  filter(n_distinct(sender.id) > 2) %>%
  ungroup()
```

```{r}
d.allmsg <- d.allmsg %>%
  left_join(d.all %>%
            select(gameID, playerID, exitSurvey), 
            by = c("gameID", "sender.id" = "playerID"))  %>%
#  mutate(usedCalculator = str_extract(exitSurvey, '(?<="usedCalculator":")[^"]*'),
mutate(exitSurvey = if_else(str_detect(exitSurvey, '"usedCalculator":"yes"'),
                                  "yes",
                                  "no")) %>% unique()
```

```{r}
summary_data <- d.allmsg %>%
  filter(!coding == 'o') %>%
  group_by(gameID) %>%
  summarize(
    exitSurvey = if_else(any(str_detect(exitSurvey, 'yes')), "yes", "no"),
    avg_error = mean(error[round == 8], na.rm = TRUE),
    pn_count = sum(str_count(coding, "pn")),
    sn_count = sum(str_count(coding, "sn")),
    pb_count = sum(str_count(coding, "pb")),
    sb_count = sum(str_count(coding, "sb"))
  ) 


summary_data_long <- summary_data %>%
  select(gameID, exitSurvey, avg_error, pn_count, sn_count, pb_count, sb_count) %>%
  pivot_longer(cols = c(pn_count, sn_count, pb_count, sb_count), 
               names_to = "message_type", values_to = "count")

summary_data_long$decile <- cut(summary_data_long$avg_error, 
                                breaks = quantile(summary_data_long$avg_error, probs = seq(0, 1, 0.2), na.rm = TRUE), 
                                include.lowest = TRUE, labels = FALSE)

summary_data_long_proportions <- summary_data_long %>%
 # filter(exitSurvey == 'no') %>%
  group_by(decile) %>% 
  mutate(total_count = sum(count)) %>% 
  group_by(decile, message_type) %>%
  summarize(proportion = sum(count) / mean(total_count)
  ) 

# Plotting
summary_data_long_proportions %>%
  mutate(message_type = fct_relevel(message_type, "pn_count", 'pb_count',  'sn_count', 'sb_count')) %>%
  ggplot(aes(x = factor(decile),  y = proportion, fill = message_type)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_brewer(palette = 'Accent', 
                    labels = c("pn_count" = "personal number", "sn_count" = "social number",
                               "pb_count" = "personal belief", "sb_count" = "social belief")) +
  labs(title = "",
       x = "error (binned)",
       y = "proportion",
       fill = "message type") +
  theme(aspect.ratio = 1, legend.position = "top") +
  guides(fill = guide_legend(nrow = 2))
```

```{r}
d.allmsg2 <- d.allmsg %>%
  group_by(gameID, sender.id) %>%
  mutate(nCrittersGame = sum(nCritters)) %>%
  ungroup()

d.allmsg2 <- d.allmsg2 %>% 
  mutate(
    entropy_minmax = ifelse(entropy <= median(entropy), "H_etpy", "E_etpy"),
    representation_minmax = ifelse(representation <= median(representation), "E_rep", "H_rep"),
    nCrittersGame_minmax = ifelse(nCrittersGame <= median(nCrittersGame), "H_crits", "E_crits"),
    group = paste(entropy_minmax, representation_minmax, nCrittersGame_minmax, sep = "\n")
  ) %>%filter(group !='E_etpy\nH_rep\nE_crits') %>%
  group_by(representation_bin, entropy_bin, nCrittersGame_bin, treatment) %>%
  mutate(errorAvg = mean(error, na.rm = TRUE)) %>% 
  ungroup() %>% 
  filter(round == 8)

summary_data <- d.allmsg2 %>%
  group_by(gameID, group) %>%
  summarize(
    avg_error = mean(error, na.rm = TRUE),
    pn_count = sum(str_count(coding, "pn")),
    sn_count = sum(str_count(coding, "sn")),
    pb_count = sum(str_count(coding, "pb")),
    sb_count = sum(str_count(coding, "sb"))
  ) %>% ungroup() %>%
  mutate(
    total_count = pn_count + sn_count + pb_count + sb_count,
    pn_prop = pn_count / total_count,
    sn_prop = sn_count / total_count,
    pb_prop = pb_count / total_count,
    sb_prop = sb_count / total_count
  )

summary_data_long <- summary_data %>%
  select(gameID, avg_error, pn_count, sn_count, pb_count, sb_count, group) %>%
  pivot_longer(cols = c(pn_count, sn_count, pb_count, sb_count), 
               names_to = "message_type", 
               values_to = "count")

# Create deciles for avg_error
decile_breaks <- unique(quantile(summary_data_long$avg_error, probs = seq(0, 1, 0.2), na.rm = TRUE))
summary_data_long$decile <- cut(summary_data_long$avg_error, 
                                breaks = decile_breaks, 
                                include.lowest = TRUE, labels = FALSE)

# Summarize to calculate proportions per decile and group
summary_data_long_proportions <- summary_data_long %>%
  group_by( group) %>% 
  mutate(total_count = sum(count)) %>% 
  ungroup() %>%
  group_by( group, message_type) %>%
  summarize(proportion = sum(count) / first(total_count), .groups = "drop")


# Set the custom order for 'group'
group_order <- c( "H_etpy\nE_rep\nH_crits", "H_etpy\nE_rep\nE_crits",
                 "E_etpy\nE_rep\nE_crits", "E_etpy\nE_rep\nH_crits", "H_etpy\nH_rep\nE_crits",
                 "E_etpy\nH_rep\nH_crits", "H_etpy\nH_rep\nH_crits", "E_etpy\nH_rep\nE_crits")

summary_data_long_proportions$group <- factor(summary_data_long_proportions$group, levels = group_order)

ggplot(summary_data_long_proportions, aes(x = group, y = proportion, fill = message_type)) +
 geom_bar(stat = "identity", position = "stack") +
 theme_few() +
 labs(title = "Proportion of Message Types by Group",
      x = "Group", 
      y = "Proportion",
      fill = "Message Type") +
 theme(legend.position = 'top',
       axis.text.x = element_text(angle = 0, hjust = 1, vjust = 1),
       plot.margin = margin(b = 20, l = 20, r = 20, t = 20)) +
 scale_x_discrete(expand = c(0.02, 0.02)) +
 theme(aspect.ratio = 0.5) # Made plot wider by reducing aspect ratio
```
