---
title: "Experiment1"
format: html
editor: visual
---

# Import packages

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}

library(conflicted)  
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")

library(tidyverse)
library(tidyboot)
library(lme4)
library(here)
library(jsonlite)
library(ggthemes)
```

## Read in data

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
d.1 <- bind_rows(
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-2101/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2234/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2246/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-21-0329/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-1731/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/11-26-1646/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-1848/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2022/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2134/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2211/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2051/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2201/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2348/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0302/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0431/playerStage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-10-0257/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-10-0433/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-11-2206/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-14-2139/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2124/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2245/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0217/playerStage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0243/playerStage.csv'))
)

d.2 <- bind_rows(
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-2101/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2234/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2246/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-21-0329/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-1731/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-26-1646/round.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-1848/round.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2022/round.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2134/round.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2211/round.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2051/round.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2201/round.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2348/round.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0302/round.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0431/round.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-10-0257/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-10-0433/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-11-2206/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-14-2139/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2124/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2245/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0217/round.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0243/round.csv'))
)%>% 
  rename(roundID = id) 

d.3 <- bind_rows(
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-2101/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2234/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2246/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-21-0329/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-1731/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-26-1646/stage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-1848/stage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2022/stage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2134/stage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2211/stage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2051/stage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2201/stage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2348/stage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0302/stage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0431/stage.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-10-0257/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-10-0433/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-11-2206/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-14-2139/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2124/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2245/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0217/stage.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0243/stage.csv'))
)%>% 
  rename(stageID = id)%>%
  rename(stageName = name)

d.5 <- bind_rows(
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-2101/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2234/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2246/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-21-0329/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-1731/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-26-1646/playerGame.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-1848/playerGame.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2022/playerGame.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2134/playerGame.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2211/playerGame.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2051/playerGame.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2201/playerGame.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2348/playerGame.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0302/playerGame.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0431/playerGame.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-10-0257/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-10-0433/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-11-2206/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-14-2139/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2124/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2245/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0217/playerGame.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0243/playerGame.csv'))
)


d.6 <- bind_rows(
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-2101/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2234/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2246/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-21-0329/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-1731/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-26-1646/player.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-1848/player.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2022/player.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2134/player.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2211/player.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2051/player.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2201/player.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2348/player.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0302/player.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0431/player.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-10-0257/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-10-0433/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-11-2206/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-14-2139/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2124/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2245/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0217/player.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0243/player.csv'))
)%>% 
  rename(playerID = id) %>% 
  select(-contains("LastChangedAt")) %>%
  filter(ended == "game ended")

d.8 <- bind_rows(
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-2101/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2234/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2246/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-21-0329/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-1731/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-26-1646/game.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-1848/game.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2022/game.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2134/game.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2211/game.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2051/game.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2201/game.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2348/game.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0302/game.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0431/game.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-10-0257/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-10-0433/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-11-2206/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-14-2139/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2124/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2245/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0217/game.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0243/game.csv'))
)%>% 
  rename(gameID = id)

d.9 <- bind_rows(
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-2101/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2234/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-20-2246/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-21-0329/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-22-1731/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/11-26-1646/batch.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-1848/batch.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2022/batch.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2134/batch.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-02-2211/batch.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2051/batch.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2201/batch.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-03-2348/batch.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0302/batch.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-04-0431/batch.csv')),
 read_csv(here('data/2_experiment_2_rare_distrib/01-10-0257/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-10-0433/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-11-2206/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-14-2139/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2124/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-17-2245/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0217/batch.csv')),
  read_csv(here('data/2_experiment_2_rare_distrib/01-19-0243/batch.csv'))
)%>% 
  rename(batchID = id)

decode1 <- read_json(here('analysis/2_simulations/generated_files_used/games_dontoverwrite.json'), simplifyVector = TRUE) %>%
  as_tibble() %>%
  rename(nCrittersGame = totalCritters) %>%
  rename(designatedGame = gameID)%>%
   filter(designatedGame != 10120) %>%
  mutate(representation = as.character(representation))

decode3 <- read_json(here('analysis/2_simulations/generated_files_used/games_2_dontoverwrite.json'), simplifyVector = TRUE) %>%
  as_tibble() %>%
  rename(nCrittersGame = totalCritters) %>%
  rename(designatedGame = gameID)%>%
  mutate(nCrittersGame = as.integer(nCrittersGame)) %>%
  mutate(representation = as.character(representation))

decode <- bind_rows(decode1, decode3)

```

## Merge files

```{r}
d.gamebatch <- merge(d.8, d.9, by = c("batchID"), all=T)%>%
  select(-contains("LastChangedAt"))

d.playergamebatch <-merge(d.6, d.gamebatch, by="gameID", all = T)

d.59 <-merge(d.playergamebatch,d.5, by = c("gameID", "playerID"), all = T)%>%
  select(-contains("LastChangedAt"))

rm(d.8, d.9, d.6, d.gamebatch, d.playergamebatch, d.5)

d.stageID <- merge(d.1, d.3, by = c("stageID", "gameID", "roundID"), all = T) %>%
  select(-contains("LastChangedAt"))


d.playerstageround <-merge(d.stageID,d.2, by = c("roundID", "gameID"), all = T)%>%
  select(-contains("LastChangedAt"))%>%
  select(gameID, stageName, roundID, confidence, guess, playerID, stageID,idx)

rm(d.1, d.2, d.stageID, d.3)

d.all <-merge(d.playerstageround,d.59, by = c("playerID", "gameID"), all = T)%>%
  select(gameID, playerID, stageName, treatmentName.x, ended.x, roundID, confidence, guess, stageID.x, idx, emojiArray, exitSurvey, participantID, recipient,treatment.x, chat,messages, participantIdentifier)%>%
  mutate(
    emojiArray = str_remove_all(emojiArray, "\\s"),
    emojiArray = str_extract_all(emojiArray, "🐇|🐿️"),
    nRabbits = sapply(emojiArray, function(x) sum(x == "🐇")),
    nSquirrels = sapply(emojiArray, function(x) sum(x == "🐿️")),
    nCritters = nSquirrels + nRabbits,
    mleEstimate = nRabbits / (nRabbits + nSquirrels)
  ) 

rm(d.59, d.playerstageround)
```

## calculations to merge desired with played games

```{r}
d.allgameplayers <- d.all %>%
   distinct(playerID, gameID, .keep_all = TRUE) %>%
  group_by(gameID) %>%
  mutate(
    nRabbitsGame = sum(nRabbits, na.rm = TRUE),
    nSquirrelsGame = sum(nSquirrels, na.rm = TRUE),
    nCrittersGame = sum(nCritters, na.rm = TRUE),
    mleGame = round(nRabbitsGame / (nRabbitsGame + nSquirrelsGame),4),
    prob = round(nCritters / nCrittersGame, 4),
    entropy = round(-sum(ifelse(prob > 0, prob * log(prob), 0)), 4),
    representation = round(mean(abs(mleEstimate - mleGame)), 4)
  ) %>%
  ungroup()

d.gamelist <- d.allgameplayers%>%
  group_by(gameID) %>%
  slice(1) %>% 
  ungroup()

```

```{r}
n_unique <- nrow(unique(decode[c("nCritters", "mleGame")]))
n_unique

dup_rows <- decode  %>%
  group_by(nCrittersGame, mleGame) %>%
  filter(n() > 1) %>%
  count(designatedGame) %>%
  filter (n==1)

duplicated_rows <-decode %>%
  filter(designatedGame %in% dup_rows$designatedGame)

# Print the rows
print(dup_rows)

#looks like 10297 and 3627 are randomly generated identical pairs and 16039 only differs by one (so representation is different)
d.decode <- decode%>%
  distinct(designatedGame, .keep_all = TRUE)
```

```{r}
d.allgameplayers <- d.allgameplayers %>%
  mutate(across(c(nCrittersGame, representation, entropy), as.character))

d.decode <- d.decode %>%
  mutate(across(c(nCrittersGame, representation, entropy), as.character))

d.allgameplayers <- d.allgameplayers %>%
  mutate(representation_formatted = sprintf("%.3f", as.numeric(representation)))

d.decode <- d.decode %>%
  mutate(representation_formatted = sprintf("%.3f", as.numeric(representation)))

d.allgameplayers <- d.allgameplayers %>%
  left_join(
    d.decode %>%
      distinct(
        nCrittersGame, nRabbitsGame, nSquirrelsGame, mleGame, representation_formatted, designatedGame, entropy_bin, representation_bin, nCrittersGame_bin
      ),
    by = c("nCrittersGame", "nRabbitsGame", "nSquirrelsGame", "mleGame", "representation_formatted")
  )


d.all <- d.all %>%
  left_join(
    d.allgameplayers %>%
      select(nSquirrelsGame, nRabbitsGame, nCrittersGame, gameID, mleGame, prob, entropy, representation, designatedGame, entropy_bin, representation_bin,nCrittersGame_bin) %>%
      distinct(gameID, .keep_all = TRUE), 
    by = c("gameID")
  )

#d.allgameplayers <- d.allgameplayers %>%
#  filter(!is.na(designatedGame))
#removes the one w 5 players
```

## Count which games are present

```{r}
decode <- decode %>%
  mutate(across(c(nCrittersGame, representation, designatedGame), as.character))

d.allgameplayers <- d.allgameplayers %>%
  mutate(across(c(nCrittersGame, representation, designatedGame, treatmentName.x), as.character))

d.count.chat <- d.allgameplayers %>%
  filter(str_ends(treatmentName.x, "interactive"))

d.count.slider <- d.allgameplayers %>%
  filter(str_ends(treatmentName.x, "slider"))


# Count the occurrences of each designatedGame in decode
decode_counts <- decode %>%
  count(designatedGame, name = "decode_count")

# Count the occurrences of each designatedGame in d.count.chat
chat_counts <- d.count.chat %>%
  count(designatedGame, name = "chat_count")

# Count the occurrences of each designatedGame in d.count.slider
slider_counts <- d.count.slider %>%
  count(designatedGame, name = "slider_count")

# Join counts to compare
missing_chat <- decode_counts %>%
  left_join(chat_counts, by = "designatedGame") %>%
  filter(is.na(chat_count) | decode_count > chat_count)

missing_slider <- decode_counts %>%
  left_join(slider_counts, by = "designatedGame") %>%
  filter(is.na(slider_count) | decode_count > slider_count)

# Print missing games for each
cat("Missing or insufficient games in d.count.chat:\n")
print(missing_chat)

cat("\nMissing or insufficient games in d.count.slider:\n")
print(missing_slider)

```

```{r}
d.allnovel <- d.all %>%
  filter(is.na(designatedGame)) %>%
  group_by(gameID) %>%
  distinct(playerID, .keep_all = TRUE) %>%
  mutate(
    countRabbits = list(nRabbits),
    countSquirrels = list(nSquirrels)
  ) %>%
  ungroup()

#10120 turns out to be the problem. generated 5 players (?)
#games ran with 4, making them novel
#filtered out above
d.modified <- d.all %>%
  filter(is.na(designatedGame))%>%
  mutate(
    designatedGame = 0,
    entropy_bin = '(0.81,1.1]',
    representation_bin = '(0.24,0.36]',
    nCrittersGame_bin = '(20,25]'
  )
d.all$designatedGame <- as.character(d.all$designatedGame)
d.modified$designatedGame <- as.character(d.modified$designatedGame)


d.allExperimental <- d.all %>% 
  bind_rows(d.modified)


d.all <- d.all %>% 
  #filter(!is.na(designatedGame))%>%
  bind_rows(d.modified)
```

```{r}
d.allf <- d.all %>%  
  separate(treatmentName.x, into = c("direction", "treatment"), sep = "_")%>% 
  filter(stageName != 'send') %>% 
  filter (!is.na(treatment))
```

```{r}
d.allf <- d.allf %>%
  mutate(nCritters = nSquirrels + nRabbits,    
         mleEstimate = nRabbits / (nRabbits + nSquirrels)) %>%
  group_by(gameID, idx) %>%
  mutate(
    nRabbitsGame = sum(nRabbits),
    nSquirrelsGame = sum(nSquirrels),
    mleGame = nRabbitsGame / (nRabbitsGame + nSquirrelsGame),
    totalCritters = sum(nCritters),
    prob = nCritters / totalCritters
  ) %>%
  mutate(
    entropy_new = -sum(ifelse(prob > 0, prob * log(prob), 0)),  # entropy per gameID
    representation = mean(abs(mleEstimate - mleGame))
  ) %>%
  ungroup() %>%
  mutate(
    entropy_bin = cut(entropy_new, breaks = seq(0, 2, .27), right = TRUE, include.lowest = TRUE, dig.lab = 2), 
    representation_bin = cut(representation, breaks = seq(0, 1, .12), right = TRUE, include.lowest = TRUE, dig.lab = 2),
    nCrittersGame_bin = cut(totalCritters, breaks = seq(15, 100, by = 5), right = TRUE, include.lowest = TRUE)
  ) %>% 
  mutate(error = if_else(direction == "RS", abs((100-guess) - (mleGame*100)), abs(guess - (mleGame*100)))) 
```

```{r}

d.allf %>%
  group_by(idx) %>%
  summarise(na_count = sum(is.na(error))) %>%
  ggplot(aes(x = idx, y = na_count)) +
  geom_line() +
  labs(x = "Index", y = "NA Count", title = "NA Count Over Time") +
  theme_minimal() 

```

```{r}
d.allf  %>%
  filter(!is.na(guess))%>%
  group_by(treatment, idx, gameID) %>%
  summarize(
    mean_error = mean(error, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  ggplot(aes(x = idx, y = mean_error, color = treatment, linetype = treatment == 'interactive')) +
    geom_point() +
    geom_smooth(method = 'lm', formula = y ~ poly(x, 2), se = F) +
    geom_hline(yintercept = c(0), linetype = 'dotted') +
    theme_few() +
    scale_color_brewer(palette = 'Accent') +
    guides(linetype = 'none') +
    scale_x_continuous(breaks = c(1,3,5,7,9,11)) +
    labs(y = 'average error', x = 'round #', color = '') +
    theme(aspect.ratio = 1, legend.position = 'top')

```

```{r}
persistentnoClick <- data.frame(gameID = character(), playerID = character(), idx = integer(), stringsAsFactors = FALSE)

for (i in 1:7) {
  idx_pair <- c(i, i + 1)
  filtered_players <- d.allf %>%
    group_by(gameID, playerID) %>%
    filter(all(is.na(guess[idx_pair]))) %>%
    mutate(idx_missed = i) %>%  
    select(gameID, playerID, idx_missed) %>%
    distinct()
  persistentnoClick <- bind_rows(persistentnoClick, filtered_players)
}
persistentnoClick <- distinct(persistentnoClick)



persistentnoClick <- persistentnoClick %>%     
  group_by(gameID, playerID) %>% 
  summarise(idx_missed = min(idx_missed), .groups = "drop")

d.allf <- d.allf %>%                              
  left_join(persistentnoClick, by = c("gameID", "playerID")) %>% 
  mutate(persistentnoClick = if_else(!is.na(idx_missed) & idx >= idx_missed, "yes", "no")) %>% 
  select(-idx_missed)

```

```{r}
d.allf %>%
  group_by(idx) %>%
  summarise(persistent_no_click_count = sum(persistentnoClick == "yes")) %>%
  ggplot(aes(x = idx, y = persistent_no_click_count)) +
  geom_line() +
  labs(x = "Index", y = "Persistent No Click Count", title = "Persistent No Click Over Time") +
  theme_minimal()

```
