---
title: "Social Influence Models Comparison"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(ggthemes)
library(patchwork)
library(here)
```

```{r load-data}
slider_df <- read_csv(here("models/slider_degroot.csv")) %>%
  pivot_longer(cols = starts_with("Agent"), names_to = "agent", values_to = "belief") %>%
  mutate(model = "DeGroot")

count_df <- read_csv(here('models/count_version.csv')) %>%
  pivot_longer(cols = starts_with("Agent"), names_to = "agent", values_to = "belief") %>%
  mutate(model = "Count Version")

dyadic_df <- read_csv(here('models/dyadic_with_influence.csv')) %>%
  pivot_longer(cols = starts_with("Agent"), names_to = "agent", values_to = "belief") %>%
  mutate(model = "Dyadic")

# Combine all data
all_models <- bind_rows(slider_df, count_df, dyadic_df) %>%
  mutate(model = factor(model, levels = c("Slider DeGroot", "Count Version", "Dyadic")))
```

```{r individual-models, fig.width=12, fig.height=8}
# Individual model plots
slider_df %>%
  ggplot(aes(x = Trial, y = belief, color = agent)) +
  geom_point() +
  geom_smooth(method = 'loess', se = FALSE) +
  scale_color_brewer(palette = 'Set2') +
  labs(title = 'Slider DeGroot Model', 
       y = 'Belief (Proportion)', 
       x = 'Trial', 
       color = '') +
  theme_few() +
  theme(aspect.ratio = 0.8, legend.position = 'bottom')

count_df %>%
  ggplot(aes(x = Trial, y = belief, color = agent)) +
  geom_point() +
  geom_smooth(method = 'loess', se = FALSE) +
  scale_color_brewer(palette = 'Set2') +
  labs(title = 'Count Version Model', 
       y = 'Belief (Proportion)', 
       x = 'Trial', 
       color = '') +
  theme_few() +
  theme(aspect.ratio = 0.8, legend.position = 'bottom')



```
